export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS'
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS'
export const SELECT_PRODUCT_CATEGORY = 'SELECT_PRODUCT_CATEGORY'
